name: model-training
on:
  pull_request:
    branches: main
permissions: write-all
jobs:
  train_and_publish_report:
    runs-on: ubuntu-latest
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training jobs
        run: |
          python make_raw_dataset.py
          python preprocess.py
          python train.py

      # - name: Setup DVC
      #   uses: iterative/setup-dvc@v1

      # - name: Run DVC pipeline
      #   run: dvc repro

      - name: Setup CML
        uses: iterative/setup-cml@v1
      
      - name: Create and publish metrics diff report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat metrics.json >> report.md
          # echo "![](./confusion_matrix.png)" >> report.md
          # dvc metrics show --md >> report.md
          # dvc metrics diff --md main >> report.md
          
          # dvc plots diff --target predictions.csv --template confusion -x true_label -y predicted_label --show-vega main > vega.json
          # vl2png vega.json -s 1.5 > confusion_plot.png
          # echo "![](./confusion_plot.png)" >> report.md

          echo "Creating comment"
          cml comment create --publish=true report.md