name: hp-tuning
on:
  pull_request:
    branches: main
permissions: write-all
jobs:
  hp_tune:
    # if: startsWith(github.ref, 'refs/heads/hp_tune/')
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Run training jobs
      #   run: |
      #     python make_raw_dataset.py
      #     python preprocess.py
      #     python train.py

      # - name: Setup DVC
      #   uses: iterative/setup-dvc@v1

      # - name: Run DVC pipeline
      #   run: dvc repro

      # - name: Setup CML
      #   uses: iterative/setup-cml@v1

      # - name: Setup node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      
      - name: Create hp
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          branch_name="${GITHUB_HEAD_REF}"
          # branch_name="${branch_name#refs/heads/}"
          echo "Branch name is $branch_name"

          git config --global --add safe.directory /__w/ml-cicd/ml-cicd
          echo 2 > rfc_forest_depth.txt
          cat rfc_forest_depth.txt
          export BRANCH_NAME=train/$(python -c "import uuid; print(str(uuid.uuid4()).split('-')[-1])")
          # cml pr create --user-email hp-bot@cicd.ai --user-name HPBot --message "HP tuning" --branch $BRANCH_NAME rfc_forest_depth.txt

      # - name: Save markdown report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: markdown-report
      #     path: ./report.md
